### ISSUE TITLE
Dockerize and add Workflow temlate to ros-package-repo-template 

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/documentation#36] opened 2020-05-10 22:15 UTC
We will need to create a base template repository for  repository using docker and docker-compose

**Comment by kevincharbonneau** [comment] 2020-05-29 17:01
closing since it's a a duplicate of [ros-package-repo-template/issue/10](https://github.com/sonia-auv/ros-package-repo-template/issues/10)

**Closed as completed by kevincharbonneau** 2020-05-29 17:01 UTC
Labels: Priority: Critical, Type: Feature
